/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cartoon.battle;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import static cartoon.battle.CartoonBattle.listUser;

/**
 *
 * @author User
 */
public class Shop extends javax.swing.JFrame {

    /**
     * Creates new form Shop
     */
    
    private void save() {
        try {            
            FileOutputStream fout = new FileOutputStream("user.dat");
            ObjectOutputStream oos = new ObjectOutputStream(fout);
            oos.writeObject(listUser);
            oos.close();
            fout.close();
        }catch (Exception e) {
            System.out.println(e);
        }
    }
    
    public Shop() {
        initComponents();
        
        //Icon Image <Wajib di tiap form>
        ImageIcon img = new ImageIcon("src\\images\\Icon.jpg");
        this.setIconImage(img.getImage());
    }
    
    public Shop(User user){
        initComponents();
        
        //Icon Image <Wajib di tiap form>
        ImageIcon img = new ImageIcon("src\\images\\Icon.jpg");
        this.setIconImage(img.getImage());
        
        //Tampilan awal
        Warning.setVisible(false);
        XMark.setVisible(false);
        ShopRanged.setVisible(true);
        BuyRanged.setVisible(true);
        RangedCost.setVisible(true);
        ShopRanged.setVisible(true);
        BuyRanged.setVisible(true);
        RangedCost.setVisible(true);

        
        Gold.setText(String.valueOf(user.getGold()));
        for (int i = 0; i < user.getTroop().size(); i++) {
            if (user.getTroop().get(i) instanceof Tank) {
                ShopTank.setVisible(false);
                BuyTank.setVisible(false);
                TankCost.setVisible(false);
            } else if (user.getTroop().get(i) instanceof Ranged) {
                ShopRanged.setVisible(false);
                BuyRanged.setVisible(false);
                RangedCost.setVisible(false);
            }
        }
        
        BuyTank.addMouseListener(new MouseAdapter(){
            public void mousePressed(MouseEvent me){
                int tempGold = user.getGold();
                if (tempGold >= 1000) {
                    tempGold-=1000;
                    user.setGold(tempGold);
                    user.addTank();
                    Gold.setText(String.valueOf(user.getGold()));
                    ShopTank.setVisible(false);
                    BuyTank.setVisible(false);
                    TankCost.setVisible(false);
                } else { //gold ga cukup
                    Warning.setVisible(true);
                    XMark.setVisible(true);
                }
                save();
            }
        });
        
        BuyRanged.addMouseListener(new MouseAdapter(){
            public void mousePressed(MouseEvent me){
                int tempGold = user.getGold();
                if (tempGold >= 1500) {
                    tempGold-=1500;
                    user.setGold(tempGold);
                    user.addRanged();
                    Gold.setText(String.valueOf(user.getGold()));
                    ShopRanged.setVisible(false);
                    BuyRanged.setVisible(false);
                    RangedCost.setVisible(false);
                } else { //gold ga cukup
                    Warning.setVisible(true);
                    XMark.setVisible(true);
                }
                save();
            }
        });
        
        BuyLaser.addMouseListener(new MouseAdapter(){
            public void mousePressed(MouseEvent me){
                int tempGold = user.getGold();                
                if (tempGold >= 150) {
                    tempGold-=150;                    
                    user.setGold(tempGold);
                    Gold.setText(String.valueOf(user.getGold()));                                                           
                    user.addSkill();
                    SkillCount.setText(String.valueOf(user.getSkill()));
                } else { //gold ga cukup
                    Warning.setVisible(true);
                    XMark.setVisible(true);
                }
                save();
            }
        });
    }

    public JButton getBack() {
        return Back;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        XMark = new javax.swing.JButton();
        Warning = new javax.swing.JLabel();
        Gold = new javax.swing.JLabel();
        SkillCount = new javax.swing.JLabel();
        RangedCost = new javax.swing.JLabel();
        BuyRanged = new javax.swing.JButton();
        TankCost = new javax.swing.JLabel();
        BuyTank = new javax.swing.JButton();
        LaserCost = new javax.swing.JLabel();
        BuyLaser = new javax.swing.JButton();
        ShopRanged = new javax.swing.JLabel();
        ShopTank = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cartoon Battle");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        XMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/X Mark.png"))); // NOI18N
        XMark.setBorderPainted(false);
        XMark.setContentAreaFilled(false);
        XMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XMarkActionPerformed(evt);
            }
        });
        getContentPane().add(XMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 140, -1, -1));

        Warning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Warning Gold.png"))); // NOI18N
        getContentPane().add(Warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Gold.setFont(new java.awt.Font("Lato Black", 1, 30)); // NOI18N
        Gold.setForeground(new java.awt.Color(255, 255, 0));
        Gold.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Gold.setText("0");
        getContentPane().add(Gold, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, 240, -1));

        SkillCount.setFont(new java.awt.Font("Lato Black", 0, 42)); // NOI18N
        SkillCount.setForeground(new java.awt.Color(255, 255, 255));
        SkillCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SkillCount.setText("0");
        getContentPane().add(SkillCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 80, -1));

        RangedCost.setFont(new java.awt.Font("Lato Black", 1, 30)); // NOI18N
        RangedCost.setForeground(new java.awt.Color(255, 255, 0));
        RangedCost.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RangedCost.setText("1500");
        getContentPane().add(RangedCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 525, 140, -1));

        BuyRanged.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Buy.png"))); // NOI18N
        BuyRanged.setBorderPainted(false);
        BuyRanged.setContentAreaFilled(false);
        BuyRanged.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyRangedActionPerformed(evt);
            }
        });
        getContentPane().add(BuyRanged, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 480, -1, -1));

        TankCost.setFont(new java.awt.Font("Lato Black", 1, 30)); // NOI18N
        TankCost.setForeground(new java.awt.Color(255, 255, 0));
        TankCost.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TankCost.setText("1000");
        getContentPane().add(TankCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 525, 140, -1));

        BuyTank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Buy.png"))); // NOI18N
        BuyTank.setBorderPainted(false);
        BuyTank.setContentAreaFilled(false);
        BuyTank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyTankActionPerformed(evt);
            }
        });
        getContentPane().add(BuyTank, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 480, -1, -1));

        LaserCost.setFont(new java.awt.Font("Lato Black", 1, 30)); // NOI18N
        LaserCost.setForeground(new java.awt.Color(255, 255, 0));
        LaserCost.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LaserCost.setText("150");
        getContentPane().add(LaserCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 525, 140, -1));

        BuyLaser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Buy.png"))); // NOI18N
        BuyLaser.setBorderPainted(false);
        BuyLaser.setContentAreaFilled(false);
        BuyLaser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyLaserActionPerformed(evt);
            }
        });
        getContentPane().add(BuyLaser, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 480, -1, -1));

        ShopRanged.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Shop Ranged.png"))); // NOI18N
        getContentPane().add(ShopRanged, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, -1, -1));

        ShopTank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ShopTank.png"))); // NOI18N
        getContentPane().add(ShopTank, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back.png"))); // NOI18N
        Back.setBorderPainted(false);
        Back.setContentAreaFilled(false);
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Shop Map.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuyTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyTankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuyTankActionPerformed

    private void BuyRangedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyRangedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuyRangedActionPerformed

    private void BuyLaserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyLaserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuyLaserActionPerformed

    private void XMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XMarkActionPerformed
        // TODO add your handling code here:
        Warning.setVisible(false);
        XMark.setVisible(false);
    }//GEN-LAST:event_XMarkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Background;
    private javax.swing.JButton BuyLaser;
    private javax.swing.JButton BuyRanged;
    private javax.swing.JButton BuyTank;
    private javax.swing.JLabel Gold;
    private javax.swing.JLabel LaserCost;
    private javax.swing.JLabel RangedCost;
    private javax.swing.JLabel ShopRanged;
    private javax.swing.JLabel ShopTank;
    private javax.swing.JLabel SkillCount;
    private javax.swing.JLabel TankCost;
    private javax.swing.JLabel Warning;
    private javax.swing.JButton XMark;
    // End of variables declaration//GEN-END:variables
}
